"""add human design fields to user_manifestos

Revision ID: 1a13761cd499
Revises: de2d63b91446
Create Date: 2025-12-01 08:13:20.029242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a13761cd499'
down_revision: Union[str, Sequence[str], None] = 'de2d63b91446'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_manifestos', sa.Column('birth_datetime_utc', sa.DateTime(), nullable=True))
    op.add_column('user_manifestos', sa.Column('birth_latitude', sa.Float(), nullable=True))
    op.add_column('user_manifestos', sa.Column('birth_longitude', sa.Float(), nullable=True))
    op.add_column('user_manifestos', sa.Column('birth_timezone_str', sa.String(), nullable=True))
    op.add_column('user_manifestos', sa.Column('chart_type', sa.String(), nullable=True))
    op.add_column('user_manifestos', sa.Column('chart_strategy', sa.String(), nullable=True))
    op.add_column('user_manifestos', sa.Column('chart_inner_authority', sa.String(), nullable=True))
    op.add_column('user_manifestos', sa.Column('chart_profile', sa.String(), nullable=True))
    op.add_column('user_manifestos', sa.Column('chart_incarnation_cross', sa.Text(), nullable=True))
    op.add_column('user_manifestos', sa.Column('chart_data_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_manifestos', 'chart_data_json')
    op.drop_column('user_manifestos', 'chart_incarnation_cross')
    op.drop_column('user_manifestos', 'chart_profile')
    op.drop_column('user_manifestos', 'chart_inner_authority')
    op.drop_column('user_manifestos', 'chart_strategy')
    op.drop_column('user_manifestos', 'chart_type')
    op.drop_column('user_manifestos', 'birth_timezone_str')
    op.drop_column('user_manifestos', 'birth_longitude')
    op.drop_column('user_manifestos', 'birth_latitude')
    op.drop_column('user_manifestos', 'birth_datetime_utc')
    # ### end Alembic commands ###
