"""create user_manifestos table

Revision ID: de2d63b91446
Revises: 
Create Date: 2025-12-01 02:18:18.252733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de2d63b91446'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_manifestos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_manifestos_id'), 'user_manifestos', ['id'], unique=False)
    op.create_index(op.f('ix_user_manifestos_title'), 'user_manifestos', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_manifestos_title'), table_name='user_manifestos')
    op.drop_index(op.f('ix_user_manifestos_id'), table_name='user_manifestos')
    op.drop_table('user_manifestos')
    # ### end Alembic commands ###
